### ISSUE TITLE
Configurable burst of OOK for dumb devices (ENER0002 and MIHO002)

### ISSUE THREAD

**Issue by mehstg** [gpbenton/engMQTTClient#10]
Hi,

I have just switched to your client after using the Energenie gateway. I have managed to integrate it with Home Assistant and all is working well. When sending an on/off signal from the official gateway, it repeatedly sends the command for around 20 seconds to give the end devices a better chance of receiving. Would it be possible to do something similar with your client?

Also, do you use the MIHO008 wall switches in your personal set-up? I assumed they used the same legacy OOK protocol, but I have found them to be very unreliable with the ener314-rt board and your client.

Paul

**Comment by gpbenton** [comment]
The current code sends the same message 8 times, which takes about 250ms, and works well for me, so sending for 20s seems a bit excessive.  

The longer it transmits, the less time there is available for receiving FSK messages, and the longer you have to wait before a second command is sent.

What I can do is make the number of transmits configurable, to allow for different configurations.  

The relevant line is 261 in dev_HRF.c.  If you increase 8 to a larger number, you can experiment yourself.  To allow multiple commands to happen after each other, you also need to alter line 281.

I don't have any MIHO008, but from the website they appear to use the same protocol, so should work in the same way.  

I have found adjusting the orientation of the PI slightly can make a difference to the radio communication, so I would suggest that.

**Comment by mehstg** [comment]
Thanks for the response. I am no C dev, but will take a look and see how I get on!

I am thinking my issue now is interference on the 433mhz frequency, so need to get to the bottom of that really!

**Comment by gpbenton** [comment]
Added -r option to specify the number of times the ook message is sent.

**Comment by mehstg** [comment]
Brilliant. Thanks for adding that.
