### ISSUE TITLE
MQTT authentication

### ISSUE THREAD

**Issue by orbsmiv** [gpbenton/engMQTTClient#13]
Are there any plans to support MQTT server authentication options, e.g. user/password or client certs?

**Comment by gpbenton** [comment]
I don't need it, so I'm not likely to develop it, but I am quite happy to accept a PR.  

Authentication shouldn't be that hard, to change - the mqtt connect call takes the parameters, and you have to add that to the command line.

SSH his a whole other kettle of fish, and I'm really not sure anyone would ever need that.

**Comment by davet2001** [comment]
I have this working for me and have submitted a PR.

**Comment by gpbenton** [comment]
PR Merged
