### ISSUE TITLE
Heat demand signal

### ISSUE THREAD

**Issue by betzuka** [gpbenton/engMQTTClient#14]
I've installed your app and it works great for controlling eTRV.

How do you derive the heat demand signal to switch on the boiler? Is this just that the eTRV target temperature is greater than the reported temperature so you assume the eTRV is open and rely on the boiler bypass if the eTRV closes between reporting periods?

**Comment by gpbenton** [comment]
I am not sure I completely understand your question.

In my house, I do not have remote control of the boiler, so it comes on at set times.  The eTRVs continue to operate whether the boiler is on or not - but obviously they will be open if the detected temperature is too low.

If nobody is home, the eTRVs are set to a low temperature, but the boiler comes on anyway.

**Comment by betzuka** [comment]
I was trying to avoid the boiler coming on when there is no demand for heat.
I my house I have a number of heating zones, each controlled with a normal two port motorised valve, this is a normal 'S' plan setup for central heating. When any one of these valves is opened it has a micro switch inside that closes when the valve has fully opened and switches the switched live into the boiler causing the boiler to produce heat and run the central heating pump to start circulation. If you have multiple zones then these micro switches are effectively OR'd into the boilers switched live connection together with an identical valve on your hot water tank so this can demand heat too.
Within each of these heating zones there are a number of rads, each with an eTRV. I derive an eTRV's demand for heat from the fact that its set temp is greater than than its reported temp. If in a zone one or more eTRVs are demanding heat then that zones valve is opened using a relay and the boiler comes on (if it is not already on).
So generally this means when all the eTRV is closed the boiler is not producing heat. All the edge cases where eTRVs have closed themselves within a reporting period or are in the process of opening are taken care of because the boiler has a bypass meaning when it it cant pump any hot water around the system it effectively circulates within the boiler itself and the boiler backs off eventually switching off.
I was looking for a cleaner signal from the eTRV that it is actually demanding heat right now to reduce or eliminate the wasted energy through the bypass.
From your description your setup must also rely on the bypass or an always open rad that has no TRV on it. When your timer switches on the boiler and the eTRVs are all closed it must be circulating heat through the bypass and backing off the boiler.
    On Thursday, 1 November 2018, 10:19:35 GMT, gpbenton <notifications@github.com> wrote:  
 
 
I am not sure I completely understand your question.

In my house, I do not have remote control of the boiler, so it comes on at set times. The eTRVs continue to operate whether the boiler is on or not - but obviously they will be open if the detected temperature is too low.

If nobody is home, the eTRVs are set to a low temperature, but the boiler comes on anyway.

**Comment by gpbenton** [comment]
I am afraid the energenie only reports anything at a minimum of every 5 minutes, so you will have to rely on the bypass for up to that length of time.  Even then, there isn't really any feedback from the eTRV on the exact state of the device.  It has been a frustration ever since I got them, and was surprised since they had gone to all the trouble of creating a two way 433MHz protocol.
