### ISSUE TITLE
How to send decimal target temperatures?

### ISSUE THREAD

**Issue by bwims** [gpbenton/engMQTTClient#15]
The target temperature is a string, yet any decimal value specified gets truncated to the nearest integer.  Is this the expected behaviour of the Energenie TRV?  A whole degree is a lot of heat.

**Comment by gpbenton** [comment]
I did have it on my list to handle decimal places, or at least half degree values. But with use I found that the temperature reported was not stable when set - it can vary up to 1.5 degrees, so setting the target any more accurately was not of much use.

If you your trvs are more stable than mine, I am willing to accept patches, but I won't be able to test them until next October when my heating comes back on.
