### ISSUE TITLE
ENER002 pairing

### ISSUE THREAD

**Issue by tillykeats** [gpbenton/engMQTTClient#20]
Hi @gpbenton 

Excellent work. I note you crafted a systemd unit config file for this, sorry, I have been in Saudi where internet outside to the real world was difficult (eyes-roll)

Graham, I've got the TRV working with default settings, in OpenHAB, but I cant get the ENER002 sockets working using your MQTT client
The hrf driver recognises my commands to the action topics such as /energenie/ENER002/..
but the socket is just flashing red, slowly. no switching.
The red led is flashing (usually have to hold it to pair) but it does nothing. 
All I get is

`Feb 05 15:39:56 openhab sh[4671]: [stderr] 20200205 15:39:56.668 DEBUG    MQTTClient- send NIL command for sensorId 7922
Feb 05 15:39:56 openhab sh[4671]: [stderr] 20200205 15:39:56.715 INFO     MQTTClient- SensorId=7922 Temperature=19
Feb 05 15:40:20 openhab sh[4671]: [stderr] 20200205 15:40:20.522 DEBUG    hrf- Receiving Message 14
Feb 05 15:40:20 openhab sh[4671]: [stderr] 20200205 15:40:20.523 DEBUG    hrf-  ManufacturerID=0x4
Feb 05 15:40:20 openhab sh[4671]: [stderr] 20200205 15:40:20.523 DEBUG    hrf-  ProductID=0x3
Feb 05 15:40:20 openhab sh[4671]: [stderr] 20200205 15:40:20.523 DEBUG    hrf-  SensorID=0x001f48
Feb 05 15:40:20 openhab sh[4671]: [stderr] 20200205 15:40:20.523 DEBUG    hrf-  ParameterID=Report Temperature
Feb 05 15:40:20 openhab sh[4671]: [stderr] 20200205 15:40:20.523 DEBUG    hrf-  value=19.6016
Feb 05 15:40:20 openhab sh[4671]: [stderr] 20200205 15:40:20.523 DEBUG    hrf-  ParameterID=CRC
Feb 05 15:40:20 openhab sh[4671]: [stderr] 20200205 15:40:20.523 DEBUG    hrf-  CRC OK
Feb 05 15:40:20 openhab sh[4671]: [stderr] 20200205 15:40:20.523 INFO     hrf- Msg=14, SensorId=8008, Temperature=19.6016
Feb 05 15:40:20 openhab sh[4671]: [stderr] 20200205 15:40:20.523 DEBUG    MQTTClient- send NIL command for sensorId 8008
Feb 05 15:40:20 openhab sh[4671]: [stderr] 20200205 15:40:20.570 INFO     MQTTClient- SensorId=8008 Temperature=19.6016

HERE GRAHAM:----
Feb 05 15:41:00 openhab sh[4671]: [stderr] 20200205 15:41:00.223 DEBUG    hrf- Switch 1 On
Feb 05 15:41:01 openhab sh[4671]: [stderr] 20200205 15:41:01.860 DEBUG    hrf- Switch 2 On
Feb 05 15:41:03 openhab sh[4671]: [stderr] 20200205 15:41:03.660 DEBUG    hrf- Switch 3 On
Feb 05 15:41:05 openhab sh[4671]: [stderr] 20200205 15:41:05.454 DEBUG    hrf- Switch 4 On
`
You promote "your client" on various forums, but with little explanations...seemingly

so

How do I control the sockets ENER002 that you claim to be able to command using "your client "...

i can't see how it works??

**Comment by gpbenton** [comment]
When you have the sockets in flashing mode, you need to send a valid command to them from a 433 MHz transmitter, either from the RPI using engMQTTClient, or some other remote control.

The socket then remembers that command, and reacts to it when the command is sent again.  This is standard for all 433MHz receivers.

The ENER002 accepts two different controllers, so you can either use one as the remote and one as the engMQTTClient, or you can use two remotes and use a scanning program to detect and mimic one of them from engMQTTClient.  I use both methods for different switches.

**Comment by tillykeats** [comment]
many thanks for your reply Graham

i have just one more question,
with one of the ENER002 plugged in,  the red led flashing,  i send a
command using the default address with your engMQTTClient running on local
host with defaults...

mosquitto_pub -t /energenie/ENER002/<default address>/0
 -m On

and hrf output confirms i sent the On command...

 , but the socket continues to flash slowly. i also tried socket numbers 1
to 4 (instead of 0) but still doesnt work.

if i hold the socket button in for 3 secs,  it flashes quickly for 2 secs
then goes back to slow flash

???

**Comment by tillykeats** [comment]
many thanks for your reply Graham

i have just one more question,
with one of the ENER002 plugged in,  the red led flashing,  i send a
command using the default address with your engMQTTClient running on local
host with defaults...

mosquitto_pub -t /energenie/ENER002/<default address>/0
 -m On

and hrf output confirms i sent the On command...

 , but the socket continues to flash slowly. i also tried socket numbers 1
to 4 (instead of 0) but still doesnt work.

if i hold the socket button in for 3 secs,  it flashes quickly for 2 secs
then goes back to slow flash

im using  debian buster on a Pi3b ... and energenie eTRVs with your
excellent client, they work fine

???

**Comment by gpbenton** [comment]
> if i hold the socket button in for 3 secs,  it flashes quickly for 2 secs
> then goes back to slow flash

This doesn't sound correct to me.  When the device is in pairing mode, it should flash rapidly until a command is received, and then the led should turn off or on, depending on the state of the switch.

I don't remember what slow flashing means, you will have to look that up in the manual.

**Comment by tillykeats** [comment]
Fixed. 
One has to ensure the switch is off (led off). Then hold the green button for 3 secs , the red led flashes quickly and you must send the 'On' command within 3 secs, Then send 'Off' , now the socket is paried.
