### ISSUE TITLE
Missing: end_trv_command script (HA package file)

### ISSUE THREAD

**Issue by tillykeats** [gpbenton/engMQTTClient#21]
Using the HomeAssistant package from here: https://github.com/gpbenton/engMQTTClient/wiki/HomeAssistantPackage

All running fine, well, almost! HA is complaining:
snippet of journalctl -u homeassistant...

Feb 29 12:47:54 pi hass[21726]: 2020-02-29 12:47:54 INFO (MainThread) [homeassistant.helpers.script] Script send_report_diagnostics_dad: Running script
Feb 29 12:47:54 pi hass[21726]: 2020-02-29 12:47:54 INFO (MainThread) [homeassistant.helpers.script] Script send_report_diagnostics_dad: Executing step call service
Feb 29 12:47:54 pi hass[21726]: 2020-02-29 12:47:54 ERROR (MainThread) [homeassistant.components.script] Error executing script script.send_report_diagnostics_dad. Service not found for call_service at pos 1: Unable to find service script/send_trv_command
Feb 29 12:47:54 pi hass[21726]: 2020-02-29 12:47:54 ERROR (MainThread) [homeassistant.core] Error executing service <ServiceCall script.send_report_diagnostics_dad (c:aeb8ddca329d4bb58110ce55cba69214)>
Feb 29 12:47:54 pi hass[21726]: Traceback (most recent call last):
Feb 29 12:47:54 pi hass[21726]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 1238, in _safe_execute
Feb 29 12:47:54 pi hass[21726]:     await self._execute_service(handler, service_call)
Feb 29 12:47:54 pi hass[21726]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 1253, in _execute_service
Feb 29 12:47:54 pi hass[21726]:     await handler.func(service_call)
Feb 29 12:47:54 pi hass[21726]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/script/__init__.py", line 207, in service_handler
Feb 29 12:47:54 pi hass[21726]:     await script.async_turn_on(variables=service.data, context=service.context)
Feb 29 12:47:54 pi hass[21726]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/script/__init__.py", line 288, in async_turn_on
Feb 29 12:47:54 pi hass[21726]:     raise err
Feb 29 12:47:54 pi hass[21726]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/script/__init__.py", line 283, in async_turn_on
Feb 29 12:47:54 pi hass[21726]:     await self.script.async_run(kwargs.get(ATTR_VARIABLES), context)
Feb 29 12:47:54 pi hass[21726]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/script.py", line 247, in async_run
Feb 29 12:47:54 pi hass[21726]:     await self._handle_action(action, variables, context)
Feb 29 12:47:54 pi hass[21726]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/script.py", line 331, in _handle_action
Feb 29 12:47:54 pi hass[21726]:     await self._actions[_determine_action(action)](action, variables, context)
Feb 29 12:47:54 pi hass[21726]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/script.py", line 413, in _async_call_service
Feb 29 12:47:54 pi hass[21726]:     context=context,
Feb 29 12:47:54 pi hass[21726]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/service.py", line 101, in async_call_from_config
Feb 29 12:47:54 pi hass[21726]:     domain, service_name, service_data, blocking=blocking, context=context
Feb 29 12:47:54 pi hass[21726]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 1205, in async_call
Feb 29 12:47:54 pi hass[21726]:     raise ServiceNotFound(domain, service) from None
Feb 29 12:47:54 pi hass[21726]: homeassistant.exceptions.ServiceNotFound: Unable to find service script/send_trv_command

I guess this just needs some code to publish a command on the mqtt topic, just wondering if that script is in another file not on here?

**Comment by gpbenton** [comment]
Sorry about that.  I have added the send_trv_command to the wiki page.
