### ISSUE TITLE
Missing: end_trv_command script (HA package file) NOT FIXED

### ISSUE THREAD

**Issue by tillykeats** [gpbenton/engMQTTClient#22]
Hello Graham, 
Sadly, the issue I raised here...
https://github.com/gpbenton/engMQTTClient/issues/21
...was closed by you prior to me being able to confirm correctness. Your fix does not work; same error is generated. 
Your fix needs to be inserted not at the end but after the last script in the chain, without the preceding **script** directive.. As per below:

         send_identity_bedroom:
          sequence:
            # This is written using the Script Syntax
            - service: script.send_trv_command
              data:
                id: '5460'
                command: 'Identify'

     ### HERE:-
        send_trv_command:
          sequence:
            - service: mqtt.publish
              data_template:
                topic: '/energenie/eTRV/Command/{{command}}/{{id}}'
                payload: 'ON'

**Comment by gpbenton** [comment]
Where you put the script section depends on entirely how organize your yaml.  The example I have given - having the send_trv_command in  the script section - works fine for me.   If you want to have the send_trv_command in the package section, that is fine too.

The wiki page is given as an example.  I am not going to give lessons in yaml.

**Comment by tillykeats** [comment]
I dont need lessons in yaml , others might, aside the script will not run in latest HA. HA is,  rather irritatingly, prone to changing the syntax and lexicon quite often.  this renders code that previously worked,  erroneous. it's highly annoying given the frequency.  
packages being such a source.  I just wondered why you would wish to maintain code that doesn't work, an example, i mean why bother with the hassle of questions and queries against it?
that's all

i dont really care as that's youre choice
