### ISSUE TITLE
Add some information about how to connect to ENER002 sockets

### ISSUE THREAD

**Issue by anthonyk91** [gpbenton/engMQTTClient#29]
Is it possible to add some information about how to pair or find the address of ENER002 sockets?  There doesn't seem to be any information with the original energenie documentation or source code (which just segfaults for me anyway).  It would be great to get some suggestions about how to find the address value to communicate with a socket.

**Comment by gpbenton** [comment]
The ENER002 sockets are standard 434MHz sockets, and work just like any other manufacturer's sockets.
You set the socket in to learning mode by long pressing the button.  The light flashes rapidly.  Then you send a command, in this case by sending an mqtt messsage but you could also use a 434 MHz remote control.  The socket detects the command and remembers it.  Whenever you send that command again, the switch performs the action.

**Comment by setdetnet** [comment]
...and using the MiHome software, build into this excellent MQTT client, it is only possible to control x4 sockets.

**Comment by gpbenton** [comment]
Added a wiki page https://github.com/gpbenton/engMQTTClient/wiki/Socket-and-other-OOK-addresses
