### ISSUE TITLE
Advice for Home Assistant package in wiki needed please!

### ISSUE THREAD

**Issue by bwims** [gpbenton/engMQTTClient#33]
Hello, and very many thanks for your work, especially now that I have it in a container that is easy to restart! :-)

I'd really like to use your HA package, but I'm having some weird problems.

I have a fairly recent version of HA running in a container.  Despite their example tutorials, the default configuration does not have a "homeassistant:" key anywhere.

According to the documentation, the "packages" integration needs to be preceded by "homeassistant:"

It certainly does not work without it, but even with it, I got the following configuration error:

> Invalid config for [group]: [control] is an invalid option for [group]. Check: group->group->bedroom_trv->control. (See ?, line ?).

Can you confirm that this package should work if placed at the end of configuration.yaml and preceded by homeassistant:  ?
And if possible shed any light as to what the weird error message is?

Very many thanks in advance!

B.

**Comment by bwims** [comment]
On a hunch, I removed these two lines:
          control: hidden
And the configuration worked.

What difference would that line have made?  Presumably it's now a deprecated feature? 🤷‍♂️

**Comment by gpbenton** [comment]
I seem to remember that the control: hidden resulted in the display not showing a toggle switch to toggle all the elements, but that evidently isn't supported any longer.  
It has been a couple of years since I looked at that, so I think HA has become much more strict about its yaml syntax, producing an error when previously (at least before 2020) it would have ignored it.
I have removed those lines from the example.
Thanks for pointing this out.

**Comment by bwims** [comment]
There's something else deprecated, which is that the statistics platform will soon require a statement of the form:
`state_characteristic: mean`
  which I added to get rid of the warning.  I assume that **mean** is the correct statistic here?

------------------------

One last question please, even though it's closed...
The following implies that there is a way to set the target temperature, but I cannot work it out how to do it as it is defined as a sensor.
```
        - platform: mqtt
          state_topic: "/energenie/eTRV/Command/Temperature/5460"
          name: "command_temperature_5460"
```

Is it there as a mistake, or is there something I've missed?   I would expect there to be a script with a parameter, but I'm a bit of a newbie to HA.  I'd really like to get rid of all the change node / mqtt combos!

Thanks again!

B.
